services:
  wbo:
    read_only: true
    build:
      context:  .
    ports:
      - "127.0.0.1:80:8000" # second is local container port
    volumes:
      - ./wbo-boards:/app/server-data
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
