// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {};
loadServices();

module.exports = {
  src_folders: ["tests"],
  page_objects_path: ["tests/lib/pages"],

  test_workers: {
    enabled: true,
    workers: "auto",
  },

  disable_output_boxes: true,

  exclude: ["tests/lib/**"],

  webdriver: {
    start_process: true,
    server_path: "./node_modules/.bin/geckodriver",
    cli_args: ["--log", "debug"],
    port: 4444,
    log_path: "logs",
  },

  test_settings: {
    default: {
      asyncHookTimeout: 30000,
      detailed_output: false,
      output: false,
      silent: true,
      desiredCapabilities: {
        browserName: "firefox",
        acceptInsecureCerts: true,
        alwaysMatch: {
          "moz:firefoxOptions": {
            args: ["-headless"],
          },
        },
      },
    },
  },
};

function loadServices() {
  try {
    Services.seleniumServer = require("selenium-server");
  } catch (err) {}

  try {
    Services.chromedriver = require("chromedriver");
  } catch (err) {}

  try {
    Services.geckodriver = require("geckodriver");
  } catch (err) {}
}
